// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufUser.proto

package com.venusource.protobuf;

public final class ProtobufUserOuterClass {
  private ProtobufUserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtobufUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtobufUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    java.util.List<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone> 
        getPhonesList();
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone getPhones(int index);
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    java.util.List<? extends com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder> 
        getPhonesOrBuilderList();
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder getPhonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProtobufUser}
   */
  public  static final class ProtobufUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtobufUser)
      ProtobufUserOrBuilder {
    // Use ProtobufUser.newBuilder() to construct.
    private ProtobufUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufUser() {
      id_ = 0;
      name_ = "";
      phones_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtobufUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                phones_ = new java.util.ArrayList<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone>();
                mutable_bitField0_ |= 0x00000004;
              }
              phones_.add(
                  input.readMessage(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.class, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Builder.class);
    }

    public interface PhoneOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ProtobufUser.Phone)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
       */
      int getPhoneTypeValue();
      /**
       * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
       */
      com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType getPhoneType();

      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      java.lang.String getPhoneNumber();
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      com.google.protobuf.ByteString
          getPhoneNumberBytes();
    }
    /**
     * Protobuf type {@code ProtobufUser.Phone}
     */
    public  static final class Phone extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ProtobufUser.Phone)
        PhoneOrBuilder {
      // Use Phone.newBuilder() to construct.
      private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Phone() {
        phoneType_ = 0;
        phoneNumber_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Phone(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                phoneType_ = rawValue;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                phoneNumber_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_Phone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.class, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder.class);
      }

      /**
       * Protobuf enum {@code ProtobufUser.Phone.PhoneType}
       */
      public enum PhoneType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>HOME = 0;</code>
         */
        HOME(0),
        /**
         * <code>WORK = 1;</code>
         */
        WORK(1),
        /**
         * <code>OTHER = 2;</code>
         */
        OTHER(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>HOME = 0;</code>
         */
        public static final int HOME_VALUE = 0;
        /**
         * <code>WORK = 1;</code>
         */
        public static final int WORK_VALUE = 1;
        /**
         * <code>OTHER = 2;</code>
         */
        public static final int OTHER_VALUE = 2;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static PhoneType valueOf(int value) {
          return forNumber(value);
        }

        public static PhoneType forNumber(int value) {
          switch (value) {
            case 0: return HOME;
            case 1: return WORK;
            case 2: return OTHER;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            PhoneType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                public PhoneType findValueByNumber(int number) {
                  return PhoneType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.getDescriptor().getEnumTypes().get(0);
        }

        private static final PhoneType[] VALUES = values();

        public static PhoneType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private PhoneType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:ProtobufUser.Phone.PhoneType)
      }

      public static final int PHONETYPE_FIELD_NUMBER = 1;
      private int phoneType_;
      /**
       * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
       */
      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType getPhoneType() {
        com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType result = com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType.valueOf(phoneType_);
        return result == null ? com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType.UNRECOGNIZED : result;
      }

      public static final int PHONENUMBER_FIELD_NUMBER = 2;
      private volatile java.lang.Object phoneNumber_;
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        }
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (phoneType_ != com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType.HOME.getNumber()) {
          output.writeEnum(1, phoneType_);
        }
        if (!getPhoneNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phoneNumber_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (phoneType_ != com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType.HOME.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, phoneType_);
        }
        if (!getPhoneNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phoneNumber_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone)) {
          return super.equals(obj);
        }
        com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone other = (com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone) obj;

        boolean result = true;
        result = result && phoneType_ == other.phoneType_;
        result = result && getPhoneNumber()
            .equals(other.getPhoneNumber());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + PHONETYPE_FIELD_NUMBER;
        hash = (53 * hash) + phoneType_;
        hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumber().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ProtobufUser.Phone}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ProtobufUser.Phone)
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_Phone_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_Phone_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.class, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder.class);
        }

        // Construct using com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          phoneType_ = 0;

          phoneNumber_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_Phone_descriptor;
        }

        public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone getDefaultInstanceForType() {
          return com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.getDefaultInstance();
        }

        public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone build() {
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone buildPartial() {
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone result = new com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone(this);
          result.phoneType_ = phoneType_;
          result.phoneNumber_ = phoneNumber_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone) {
            return mergeFrom((com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone other) {
          if (other == com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.getDefaultInstance()) return this;
          if (other.phoneType_ != 0) {
            setPhoneTypeValue(other.getPhoneTypeValue());
          }
          if (!other.getPhoneNumber().isEmpty()) {
            phoneNumber_ = other.phoneNumber_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int phoneType_ = 0;
        /**
         * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
         */
        public int getPhoneTypeValue() {
          return phoneType_;
        }
        /**
         * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
         */
        public Builder setPhoneTypeValue(int value) {
          phoneType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
         */
        public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType getPhoneType() {
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType result = com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType.valueOf(phoneType_);
          return result == null ? com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
         */
        public Builder setPhoneType(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          phoneType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .ProtobufUser.Phone.PhoneType phoneType = 1;</code>
         */
        public Builder clearPhoneType() {
          
          phoneType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object phoneNumber_ = "";
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public java.lang.String getPhoneNumber() {
          java.lang.Object ref = phoneNumber_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            phoneNumber_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPhoneNumberBytes() {
          java.lang.Object ref = phoneNumber_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            phoneNumber_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public Builder setPhoneNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          phoneNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public Builder clearPhoneNumber() {
          
          phoneNumber_ = getDefaultInstance().getPhoneNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public Builder setPhoneNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          phoneNumber_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:ProtobufUser.Phone)
      }

      // @@protoc_insertion_point(class_scope:ProtobufUser.Phone)
      private static final com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone();
      }

      public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Phone>
          PARSER = new com.google.protobuf.AbstractParser<Phone>() {
        public Phone parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Phone(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Phone> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Phone> getParserForType() {
        return PARSER;
      }

      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    private java.util.List<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone> phones_;
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public java.util.List<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public java.util.List<? extends com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(3, phones_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, phones_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser)) {
        return super.equals(obj);
      }
      com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser other = (com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getPhonesList()
          .equals(other.getPhonesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtobufUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtobufUser)
        com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.class, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Builder.class);
      }

      // Construct using com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhonesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.venusource.protobuf.ProtobufUserOuterClass.internal_static_ProtobufUser_descriptor;
      }

      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser getDefaultInstanceForType() {
        return com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.getDefaultInstance();
      }

      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser build() {
        com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser buildPartial() {
        com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser result = new com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (phonesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            phones_ = java.util.Collections.unmodifiableList(phones_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser) {
          return mergeFrom((com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser other) {
        if (other == com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (phonesBuilder_ == null) {
          if (!other.phones_.isEmpty()) {
            if (phones_.isEmpty()) {
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePhonesIsMutable();
              phones_.addAll(other.phones_);
            }
            onChanged();
          }
        } else {
          if (!other.phones_.isEmpty()) {
            if (phonesBuilder_.isEmpty()) {
              phonesBuilder_.dispose();
              phonesBuilder_ = null;
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000004);
              phonesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhonesFieldBuilder() : null;
            } else {
              phonesBuilder_.addAllMessages(other.phones_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone> phones_ =
        java.util.Collections.emptyList();
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = new java.util.ArrayList<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone>(phones_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder> phonesBuilder_;

      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public java.util.List<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone> getPhonesList() {
        if (phonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phones_);
        } else {
          return phonesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public int getPhonesCount() {
        if (phonesBuilder_ == null) {
          return phones_.size();
        } else {
          return phonesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone getPhones(int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);
        } else {
          return phonesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder setPhones(
          int index, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.set(index, value);
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder setPhones(
          int index, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.set(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(
          int index, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(index, value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(
          int index, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone> values) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phones_);
          onChanged();
        } else {
          phonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder removePhones(int index) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.remove(index);
          onChanged();
        } else {
          phonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder getPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder getPhonesOrBuilder(
          int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);  } else {
          return phonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public java.util.List<? extends com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder> 
           getPhonesOrBuilderList() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phones_);
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder addPhonesBuilder() {
        return getPhonesFieldBuilder().addBuilder(
            com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder addPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().addBuilder(
            index, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public java.util.List<com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder> 
           getPhonesBuilderList() {
        return getPhonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder> 
          getPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.Phone.Builder, com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser.PhoneOrBuilder>(
                  phones_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProtobufUser)
    }

    // @@protoc_insertion_point(class_scope:ProtobufUser)
    private static final com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser();
    }

    public static com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufUser>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufUser>() {
      public ProtobufUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtobufUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufUser> getParserForType() {
      return PARSER;
    }

    public com.venusource.protobuf.ProtobufUserOuterClass.ProtobufUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtobufUser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufUser_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtobufUser_Phone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtobufUser.proto\"\311\001\n\014ProtobufUser\022\n\n" +
      "\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022#\n\006phones\030\003 \003(\0132" +
      "\023.ProtobufUser.Phone\032z\n\005Phone\0220\n\tphoneTy" +
      "pe\030\001 \001(\0162\035.ProtobufUser.Phone.PhoneType\022" +
      "\023\n\013phoneNumber\030\002 \001(\t\"*\n\tPhoneType\022\010\n\004HOM" +
      "E\020\000\022\010\n\004WORK\020\001\022\t\n\005OTHER\020\002B\037\n\027com.venusour" +
      "ce.protobufZ\004userb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtobufUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtobufUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtobufUser_descriptor,
        new java.lang.String[] { "Id", "Name", "Phones", });
    internal_static_ProtobufUser_Phone_descriptor =
      internal_static_ProtobufUser_descriptor.getNestedTypes().get(0);
    internal_static_ProtobufUser_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtobufUser_Phone_descriptor,
        new java.lang.String[] { "PhoneType", "PhoneNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
